name: stream_chat_flutter_example
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  collection: ^1.15.0
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
  responsive_builder: ^0.7.0
  stream_chat_flutter:
    git:
      url: https://github.com/TheAppCrafter/stream-chat-flutter.git
      path: packages/stream_chat_flutter
  stream_chat_localizations:
    git:
      url: https://github.com/TheAppCrafter/stream-chat-flutter.git
      path: packages/stream_chat_localizations
  stream_chat_persistence:
    git:
      url: https://github.com/TheAppCrafter/stream-chat-flutter.git
      path: packages/stream_chat_persistence

flutter:
  uses-material-design: true
  assets:
    - assets/background_doodle.png
